trigger:
  branches:
    include:
      - main

variables:
  - group: aws-credentials

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Terraform_Dev
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: |
              curl -O https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
              unzip terraform_1.8.3_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
            displayName: 'Install Terraform'

          - script: |
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
              export AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN)
              cd envs/dev
              terraform init
              terraform validate
              terraform plan
              terraform apply -auto-approve
            displayName: 'Terraform Apply'
